# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul  8 13:08:10 2019
# ------------------------------------------------

package:
    name: librosa
    version: 0.7.0
source:
    fn: librosa-0.7.0.tar.gz
    md5: baa1ef65242f6ea6b75f2ab2a52d804b
    url: https://pypi.io/packages/source/l/librosa/librosa-0.7.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.1.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py27_0
        - sqlite 3.28.0 hcee41ef_1
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - audioread >=2.0.0
        - decorator >=3.0.0
        - joblib >=0.12.0
        - matplotlib >=1.5.0
        - numba >=0.38.0
        - numpy >=1.15.0
        - pysoundfile >=0.9.0
        - python
        - resampy >=0.2.0
        - scikit-learn >=0.14.0,!=0.19.0
        - scipy >=1.0.0
        - setuptools
        - six >=1.3
test:
    imports:
        - librosa
        - librosa.core
        - librosa.display
        - librosa.feature
        - librosa.util
about:
    home: http://github.com/librosa/librosa
    license: ISC
    summary: Python module for audio and music processing
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bmcfee
